### ISSUE TITLE
[🔨 lint]: integrate ` lint-staged` plugin to speedup commit checks

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#1078]
As an ESL team member, I want to have a balance between the quality of checks and their speed.

It is requested to make a commit check via the [lint-staged](https://github.com/okonet/lint-staged) plugin to limit the number of checks started for commit changes.

**Priority** Normal

**Comment by fshovchko** [comment]
I'm afraid lint-staged doesn't satisfy our needs with running eslint checks, because for some reason lint-staged renderer doesn't print out warnings. The only time it will print any of the information when eslint check finished with an error.
