### ISSUE TITLE
docs: update Exadel logo in docs and site pages

### ISSUE THREAD

**Issue by fshovchko** [exadel-inc/esl#1480]
Current Asset: ![exadel-logo-big](https://user-images.githubusercontent.com/60318924/218686049-742b9d02-0a10-4e1d-ab44-c7fa4cc28104.png)

**Comment by ala-n** [comment]
@fshovchko 
Can we experiment a little bit with the quality of the icon, mb we can also consider SVG (but there will be a problem with support  in MD renderers )
The concern is non-smooth lines on the current asset.

**Comment by fshovchko** [comment]
![exadel-logo-2](https://user-images.githubusercontent.com/60318924/219058450-8aabc87e-6cdb-40c1-8839-85849130a8b6.png)

**Comment by ala-n** [comment]
That sounds super 👍🏻 
@fshovchko , apply a new asset for the README file, please 
( adapted/resized but without significant visual artifacts; as I mentioned, the only concern was the smoothness of the logo in the README preview)
