### ISSUE TITLE
[⚡e2e]: add ability to load starting snippet for testing

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#2262]
Requirements: 

1. Open an actual test page driven by an 11ty server
    Make sure we can access any page
    e.g. home page we have for scene tests right now
    ```gherkin
       Given a page "/"
    ```
    
    Make sure we can open a test page
    ```gherkin
       Given a page "/test/testpage"
    ```
    Test page requirements:
    1. All the test pages should be stored under `test` subpath / subfolder (`site/views/test`)
    2. Recommended to use the `test` layout for snippet test pages (create if not exist, based on an empty layout)
    3. It is absolutely critical to make sure that test pages are excluded from any indexes/collections (sitemap, navigation, etc)

2. (Optional)
```gherkin
   Given a snippet:
   """html
   <div>
        Bal bla bla <my-component></my-component>
   </div>
   """  
```
  (syntax to be clarified)
  So the test env automatically opens the empty page and inserts the provided markup

**Comment by fshovchko** [comment]
Couple of things to point out:
- (Off topic) our rule `check if the screenshot is equal to the snapshoted version` has threshold of .25, which is super big. I tried deleting a header from our landing page and test still passed. The test started to fail only on threshold of .02
- I tried to implement a snippet rule. But apparently [doc strings](https://cucumber.io/docs/gherkin/reference/#doc-strings) are not supported by stucumber package that we are using. Here is the issue about the topic without any activity: https://github.com/sjmeverett/stucumber/issues/8
-  What should our test layout have? Is it going to be just a simple extension of empty layout (alias)?
