### ISSUE TITLE
[🚀esl-utils]: add the ability to use additional attributes in loadScript utility

### ISSUE THREAD

**Issue by dshovchko** [exadel-inc/esl#2278]
As an ESL consumer, I want to be able to set additional attributes to the script tag when using the [loadScript()](https://github.com/exadel-inc/esl/blob/main/src/modules/esl-utils/dom/script.ts) utility. For example `crossorigin` or `referrerpolicy` attributes.

I propose to add a third argument to the `loadScript` method signature for passing additional attributes to set them at the script element.

```ts
loadScript('script-id', 'https://unpkg.com/foo.js', {crossorigin: 'anonymous', referrerpolicy: 'no-referrer'});
```

**Comment by ala-n** [comment]
Note:
let's limit allowed settings to `crossorigin`, `referrerpolicy` and optionally `integrity` (not sure we need it, need to check if there is a possibility for such cases)
See comment in #2279 for details
