### ISSUE TITLE
[🐛 in esl-event-listener]: `DelegatedTarget` event functionality updates

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#2358]
We have implemented `DelegatedTarget` functionality for delegated event catching via ESLEventListeners.
But there are a couple of problems/improvements requested from practical usage:

- [x] There is no possibility to use `DelegatedTarget` without referencing exact Event type. But it does not matter in some cases, and we want just reverence generic type.
It is requested to declare default to Event: so we can shortcutted `onEvent(e: DelegatedEvent<Event>)` to `onEvent(e: DelegatedEvent)`

- [x] There are some types of incompatibility when `DelegatedTarget` is used:
```
  // No issue by some reason
  @listen({event: 'click', selector: (el: ESLToggleable) => el.closeTrigger || ''})
  protected _onCloseClick(e: DelegatedEvent<MouseEvent>): void {}
  
  // Type issue, but it should not be presented
  @listen({event: 'click', selector: (el: ESLToggleable) => el.closeTrigger || ''})
  protected _onCloseClick(e: DelegatedEvent<Event>): void {}
```
Note:
```
  // It is a type issue as it should be, make sure it still is
  @listen({event: 'click', selector: (el: ESLToggleable) => el.closeTrigger || ''})
  protected _onCloseClick(e: DelegatedEvent<KeyboardEvent>): void {}
```

- [x] Some similar issues may still be presented in lower APIs. Ensure no incompatibilities exist in `ESLEventUtils.subscribe` when the delegated event is used.

- [x] Just a question: does the `DelegatedTarget.$delegate` could be null ?

- [x] Make sure a declarative TS Doc provided for the feature cases

Note: some early preparations/partial fixes presented on https://github.com/exadel-inc/esl/compare/main...tech/default-delegated-type

Target: `main`

**Comment by ala-n** [comment]
Assign @abarmina as a core team observer for that issue

**Comment by fshovchko** [comment]
@ala-n, @abarmina
I replicated the issue. Looks like it was resolved with introduction with extra signature for listen method. Issue doesn't appear in lower api neither.

`DelegatedTarget.$delegate` technically can be null with they way we handle delegation. But logically it shouldn't.

**Comment by ala-n** [comment]
I'll open PR then. Regarding `null` I see, my initial understanding was the same, but still sounds dangerous so if we gonna make it non nullable lets move that change separately.
