### ISSUE TITLE
[🐛 in esl-popup]: incorrect behavior when popups trigger is inside an element with a fixed position

### ISSUE THREAD

**Issue by dshovchko** [exadel-inc/esl#380]
**Describe the 🐛 bug in component**
The following problem exists for esl-popups and esl-tooltips. If a popup trigger is inside a container with a fixed position, then in some cases the popup will not open. Or if the contents of such a container are scrolled, then when scrolling, the open popup suddenly disappears for no reason.
Usually, problems with triggers that located at the beginning of the fixed container.

The issue is reproducible in browsers without intersection observer support.

**To Reproduce**
1. Setup markup:
- place the container with position fixed to markup (but not at the very beginning of the body, perfect when it starts from the middle of the screen)
- add content to that container (it is desirable that there is a lot of content and it will be scrolled)
- add esl-popup
- place several popup triggers into the container
2. Try to open popups in different places of container
3. Try to open popup and scroll container content

**Current behavior**
The popup either does not open at all or opens, but when scrolling the contents of the container, it suddenly hides. In this case, the popup trigger has not even reached the edge of the visible area yet.

**Expected behavior**
A popup should always open when its trigger is visible.
An open popup should remain open during a scroll as long as its trigger remains fully visible.

**Environment**
- OS: Windows 10
- Browser: Internet Explorer 11
- intersection-observer polyfil: 0.12.0

**Possible Solution**
I believe that the root of the problem is in the intersection observer polyfill. There should be no check for intersection with the parents of the fixed positioned container.

**Comment by ala-n** [comment]
Closed as inactual
