### ISSUE TITLE
[🚀esl-panel-group]: add ability to collapse inner accordion when nesting accordion

### ISSUE THREAD

**Issue by julia-murashko** [exadel-inc/esl#427]
As an esl-panel-group component consumer, I want to have the ability to support inner accordion with the following behavoir:
hide event of panel is followed by all its nested panels collapsing.

Implement ESLNestedPanelGroup (ESLNestedAccordion) mixin

**Comment by ala-n** [comment]
Recommended spec (suggested bt @ala-n , @NastaLeo, @Natalie-Smirnova ):

Extend `esl-related-target` mixin.
Scope of updates:
 - [ ] make related target able to target multiple related togglable
 - [ ] make related target mixin customizable in terms of observed actions:
    introduce `esl-related-target-action` with 'hide'|'show'|'all'(default) as a values
