### ISSUE TITLE
[🚀for esl-a11y-group]: add ability to suppress scroll after focusing on the item 

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#481]
As an ESLA11yGroup consumer, I want to be able to have full control over the scroll behavior on focus.

Proposed to add an ability to define `peventScroll` boolean attribute and property to define focus behavior

`<esl-a11y-group prevent-scroll></esl-a11y-group>`
`$elGroup.preventScroll = true | false;`

**Priority**: Major

**Additional context**
New param should be passed directly to the `element.focus({preventScrall: ... })` calls of group inner implementaition

**Comment by ala-n** [comment]
@julia-murashko, could you please check the ability and relevance in terms of the original element concept?

**Comment by julia-murashko** [comment]
I believe this is a relevant request.
