### ISSUE TITLE
[🚀for esl-scrollbar]: add non bubble event on scrollbar update

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#506]
As an ESLScrollbar consumer, I want to be able to subscribe to `esl-scrollbar` updates.

Proposed to add `esl:change:position` event to be dispatched on scrollbar position updates. The event should be non-bubbled due to performance reasons.

**Priority**: Normal

**Comment by ala-n** [comment]
FYI: @yadamskaya , @andreybelous

**Comment by ala-n** [comment]
Accepted if @yadamskaya agree

**Comment by yadamskaya** [comment]
Approved!
