### ISSUE TITLE
[🚀for esl-scrollbar]: add marker attributes to detect boundary positions

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#507]
As an ESLScrollbar consumer, I want to be able to consume information when the scrollbar is in the min or max positions (very top and bottom position for vertical mode; very left and right positions for the horizontal mod)

Proposed to add markers on the scrollbar to notify about position == 0 and position == 1 states.
Posible markers names: `at-start` / `at-end` (discussable)

**Priority**: Normal

**Comment by ala-n** [comment]
FYI: @yadamskaya, @andreybelous

**Comment by ala-n** [comment]
Accepted if @yadamskaya agree

**Comment by yadamskaya** [comment]
Approved!
