### ISSUE TITLE
[🚀for esl-scrollbar]: Migrate to the pointer events standard

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#508]
As an ESL architect, I expect to have components based on modern browser features.

Request to migrate ESL Scrollbar to track PointerEvents instead of mouse/touch events.
Use a simple fallback to the mouse events if pointer events are not supported.

Please be aware that 
Safari <13 (iOS and MAC) is not supporting PointerEvents standard

**Priority**: Normal

**Comment by ala-n** [comment]
FYI: @yadamskaya , @andreybelous

**Comment by ala-n** [comment]
TO Discuss 
The first try was not successful:
- Doesn't work in iOS, does not work correctly in iOS Safari 14
- doesn't work correctly in Android (does not capture movement)

**Comment by yadamskaya** [comment]
It is not urgent, needs investigation

**Comment by ala-n** [comment]
After deeper investigation Pointer Events migration is declined for the nearest year at least due to Safari support.
Touch support added in bounds of #722
