### ISSUE TITLE
[🚀 esl-utils]: extend `esl-utils/misc/format.ts` module with capitalize method

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#519]
As an esl-utils consumer, I want to be able to transform string for some common cases like first letter capitalizing.

Request to add a `capitalize` method to make the first non-indent (space, tab, newline) letter in the string capitalized.

**API**: 
`capitalize(str: string): string;`

**Test Cases / Examples**
```
expect( capitalize('hello world') ).toBe('Hello world');
expect( capitalize('Hi') ).toBe('Hi');
expect( capitalize('') ).toBe('');
expect( capitalize('  sorry') ).toBe('  Sorry');
```

NOTE: unit test should be created for the new method

**Comment by aswinidev** [comment]
I m sorry it seems I linked 2 pull requests 
I m new to open source so I apologize for any inconvenience

**Comment by aswinidev** [comment]
I made a new PR because the old one was having some issues which I was not able to resolve. I think this one is correct
