### ISSUE TITLE
[🔨 chore]: convert `.commitlintrc.json` to Yaml language

### ISSUE THREAD

**Issue by abarmina** [exadel-inc/esl#527]
As a member of the ESL dev team, I would like to have the Conventional commit (`.commitlintrc.json`) on Yaml language, since we have the Configuring ESLint file in this language (`.eslintrc.yml`).

**Helpful links:** [YAML Cheatsheet](https://quickref.me/yaml)

**Comment by shivamchourasia4** [comment]
I would like to help.
Assign this to me

**Comment by abarmina** [comment]
Hi @shivamchourasia4! 
Thank you, we are glad to see your contribution to the ESL project!
I assign the problem to you

**Comment by ala-n** [comment]
@shivamchourasia4 really sorry, but it looks like @ek-tereshko outrun with the issue resolving.
But we will still be glad to see your help in resolving other issues.
