### ISSUE TITLE
[🔨 chore]: convert `.stylelintrc.json` to Yaml language

### ISSUE THREAD

**Issue by abarmina** [exadel-inc/esl#528]
As a member of the ESL dev team, I would like to have the Stylelint (`.stylelintrc.json`) on Yaml language, since we have the Configuring ESLint file in this language (`.eslintrc.yml`).

**Helpful links:** [YAML Cheatsheet](https://quickref.me/yaml)

**Comment by abarmina** [comment]
Hello @Ashwin-exe!
Sure! I really appreciate your help with the ESL project!
I will assign this issue to you

**Comment by Ashwin-exe** [comment]
Hey @abarmina, I fixed this issue 😃, 
But I'm having trouble while building the project locally, I also tried [contribution docs](https://github.com/exadel-inc/esl/blob/main/docs/DEVELOPMENT.md#setup-the-project) , can you help me with this ?
