### ISSUE TITLE
[🚀 gh-pages]: move html minifier to a separate file

### ISSUE THREAD

**Issue by abarmina** [exadel-inc/esl#531]
As a member of the ESL dev team, I want to have minified HTML transform moved into a separate file.

_Current state_ - this transform is in the config file `.eleventy.js`.
_Proposed state_ - this transform has been moved to a separate file.

<img width="537" alt="" src="https://user-images.githubusercontent.com/52083788/136289473-59aed168-a580-4f4a-992e-9fafe3cf9017.png">

**Related Docs:** [Transforms Example: Minify HTML Output](https://www.11ty.dev/docs/config/#transforms-example-minify-html-output)

**Comment by ala-n** [comment]
Hey @kiennguyenchi, thank you!
Issue assigned to you. We are glad to see your contribution to the ESL project.
