### ISSUE TITLE
[🐛 in gh-pages]: root (content greed) pages are not presented in sitemap

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#676]
As an esl-ui.com content manager, I want to have root (category) pages to be indexed by search engines.

The root/category pages are going to have additional content, so they are an important part of esl-ui.com site navigation. In order to have them in the search engines indexes, they should be presented in the sitemap.xml

**Suggested solution**
- return pages back into 11ty collections in order to have them collected by sitemap builder.
- choose one:
  - use a separate collection (tag) navigation to exclude them from article lists
  - use existed 'ignore' filter (but rename it to the 'hidden' please) 

**Page(s)**
https://esl-ui.com/examples/
https://esl-ui.com/components/
https://esl-ui.com/utils/

**Environment**
- [Sitemap](https://esl-ui.com/sitemap.xml)

**Comment by fshovchko** [comment]
root/category are already indexed by search engines
