### ISSUE TITLE
[🐛 in esl-panel-group]: there is no `after:show` | `after:hide` event after group animation

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#849]
As an ESL consumer, I want to have consistency in panel / panel group API. 

**Current behavior**
Currently, there is no `after:show` or `after:hide` event dispatching when the animation is handled by the panel-group (tab animation).  

**Expected behavior**
`after:hide` | `after:show` events dispatched when the panel group ends animation

**Discussion points**
 - what kind of target should be in that situation: panel-group that handles animation technically or panel that initiates state change
 - should we dispatch both show and hide events?

**Comment by ala-n** [comment]
@julia-murashko, could you please define the expected result here?

**Comment by julia-murashko** [comment]
After discussion with @ala-n Penal Group delegates events of opened and closed panels.
