### ISSUE TITLE
[🐛 in esl-toggleable]: "esl:" prefix fires with duplicate

### ISSUE THREAD

**Issue by dmantsevich** [exadel-inc/esl#913]
**Double "esl:" prefix as event name**
File: https://github.com/exadel-inc/esl/blob/main/src/modules/esl-toggleable/core/esl-toggleable.ts#L225
https://github.com/exadel-inc/esl/blob/main/src/modules/esl-base-element/core/esl-base-element.ts#L60

**To Reproduce**
```
<esl-toggleable id="myToggleable" ...></esl-toggleable>

myToggleable.addEventListener('esl:refresh', (e) => { console.log(e); }); // doesn't work
myToggleable.addEventListener('esl:esl:refresh', (e) => { console.log(e); }); // works
```

**Expected behavior**
Only one "esl:" prefix

**Screenshots**
![image](https://user-images.githubusercontent.com/3327680/162079491-60f31b5c-2028-43f8-950d-9b6dbbae51c6.png)r.

**Comment by ala-n** [comment]
Discussion related to the `esl-base-element` behaviour moved to #916 ticket with a 4.0.0 target version.
