### ISSUE TITLE
[⚡jest]: migrate to Jest v28 

### ISSUE THREAD

**Issue by ala-n** [exadel-inc/esl#961]
As an ESL contributor, I want to have jest tool version up to date. Proposed to migrate to `jest@28`.

https://jestjs.io/docs/upgrading-to-jest28

**Comment by fshovchko** [comment]
Waiting for ts-jest transformer to update to version 28
https://github.com/kulshekhar/ts-jest/issues/3453

**Comment by ala-n** [comment]
Awesome, thanks @fshovchko !
