### ISSUE TITLE
[🚀 esl-utils/listen]:  add possibility to see event handler code in the browser

### ISSUE THREAD

**Issue by NastaLeo** [exadel-inc/esl#983]
As an ESL consumer I want to be able to navigate to source code of exact event handler in the browser (event listeners tab) in case event is subscribed by @listen decorator

Example:
```ts
  // We are searching for its method
  @listen('click')
  onClick(): void {
    console.log('click');
  }
```
![image](https://user-images.githubusercontent.com/8127830/168440564-4bad1321-8c41-4866-bbfb-fb6153a01f2e.png)

**Comment by ala-n** [comment]
Really good case, thanks a ot @NastaLeo !
We need to see if there is a possibility to make exact handler function acessible with chrome dev tools.

**Comment by ala-n** [comment]
The issue was resolved by the possibility of seeing the ESLEventListener object as a DOM Event subscription when `getEventListeners($0)` is called through the browser console.
